theme: jekyll-theme-minimal
title: The Definition of Done
description: Practical steps to design, build, release, and maintain software.
remote_theme: pages-themes/slate@v0.2.0
github:
  owner_name: Al Barrera
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one