# GitHub Workflow to run tests on push and pull requests
name: Ruby HTML Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        - run: |
            gem install bundler
            bundle install
        # To run tests, run default rake task
        - run: |
            bundle exec rake
